#!/bin/sh
grep "session optional pam_exec.so /usr/local/bin/pam-sshd-attach" /etc/pam.d/sshd > /dev/null && exit
cat << EOF >> /etc/pam.d/sshd

# Attach to cgroup started by scheduler
session optional pam_exec.so /usr/local/bin/pam-sshd-attach
EOF
