#!/bin/bash
set -x
if [ x"$HOSTNAME" == x ] ; then echo HOSTNAME not set ; exit 1 ; fi

shared=4
total=8
batch=`expr $total - $shared`
qi=fji

action="${1:-off}"

if [ x"$action" == xoff ] ; then
 pbsnodes $HOSTNAME | grep jobs && { echo ERROR: node busy ; exit 1 ; }
 qmgr -c "s q ${qi} started = false" && \
  pbsnodes -C "reassigning all GPUs to batch queues" -o $HOSTNAME && \
  sed -i 's/^nshared=.*/nshared=0/' /usr/local/etc/dgx-cgroup && \
  rm -f /var/run/dgx-cgroup/map-gpu && \
  if [ -d /sys/fs/cgroup/devices/shared ] ; then cgdelete -g devices:/shared ; fi && \
  qmgr -c "set node $HOSTNAME resources_available.ngpus = $total" && \
  qmgr -c "set node $HOSTNAME resources_available.model = dgx1" && \
  qmgr -c "set node $HOSTNAME resources_available.model += dgx1-pilot" && \
  pbsnodes -C "" -r $HOSTNAME
elif [ x"$action" == xwait ] ; then
 qmgr -c "set node $HOSTNAME resources_available.model = dgx1"
elif [ x"$action" == xon ] ; then
 pbsnodes $HOSTNAME | grep jobs && { echo ERROR: node busy ; exit 1 ; }
 pbsnodes -C "reassigning ${shared} GPUs to ${qi}" -o $HOSTNAME && \
  if [ -d /sys/fs/cgroup/devices/shared ] ; then cgdelete -g devices:/shared ; fi && \
  sed -i s/'^nshared=.*$'/nshared=${shared}/ /usr/local/etc/dgx-cgroup && \
  rm -f /var/run/dgx-cgroup/map-gpu && \
  qmgr -c "set node $HOSTNAME resources_available.ngpus = $batch" && \
  qmgr -c "set node $HOSTNAME resources_available.model = dgx1" && \
  qmgr -c "set node $HOSTNAME resources_available.model += dgx1-interactive" && \
  qmgr -c "set node $HOSTNAME resources_available.model += dgx1-pilot" && \
  qmgr -c "set queue ${qi} started = true" && \
  pbsnodes -C "" -r $HOSTNAME
fi
